print("give 2 numbers to either add, subtract, multiply, divide")
number = int(input("num1: "))
number2 = int(input("num2: "))
print("what do you want")
what_to_do = int(input("1: Addition,  2: Subtraction,  3: Multiplication,  4: Division : "))
if (what_to_do == 1) : print(number+number2)
elif (what_to_do == 2) : print(number-number2)
elif (what_to_do == 3) : print(number*number2)
elif (what_to_do == 4 and number2!= 0): print(number/number2)
else: print("invalid number 2")